language: erlang
otp_release:
  - 19.3
  - 20.0
  - 21.0
  - 22.0
script:
  - "curl -fsSL https://raw.github.com/synrc/mad/master/mad > mad"
  - "chmod +x mad"
  - "./mad dep com"
  - "rebar get-deps compile"
  - "rebar3 dialyzer"
